name: App versioning
description: Action to release a new app version
inputs:
  package-name:
    description: "Package name"
    required: true
  package-filename:
    description: "Path to packege.json file"
    required: true
  github-token:
    description: ""
    required: true
outputs:
  version:
    description: ""
    value: ${{ steps.versionCheck.outputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get version from package.json
      id: versionCheck
      uses: EndBug/version-check@v2
      with:
        file-name: ${{ inputs.package-filename }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        name: @${{ inputs.package-name }}@${{ steps.versionCheck.outputs.version }}
        tag: @${{ inputs.package-name }}@${{ steps.versionCheck.outputs.version }}
        token: ${{ inputs.github-token }}
